const mongoose = require("mongoose");
const { Schema } = mongoose;

const InfoSchema = new Schema({
  grade: {type : String, required : true},
  name: {type : String, required : true},
  address: String,
  phone: String,
  cellphone: String,
  email: String,
  place_birth: String,
  date_birth: String,
  date_school: String,
  date_army: String,
  enrollment: String,
  prof_license: String,
  curp: String,
  civil_status: String,
  rfc: String,
  cta_bajio: String,
  shoe_size: String,
  size: String,
  name_primary: String,
  date_start_primary: String,
  date_end_primary: String,
  name_high_school: String,
  date_start_high_school: String,
  date_end_high_school: String,
  name_preparatory: String,
  date_start_preparatory: String,
  date_end_preparatory: String,
  name_professional: String,
  date_start_professional: String,
  date_end_professional: String,
  training_campus: String,
  promotions: String,
  dates_promotions: String,
  laguanges: String,
  name_dad: String,
  age_dad: String,
  afiliate_dad: String,
  name_mom: String,
  age_mom: String,
  afiliate_mom: String,
  name_wife: String,
  age_wife: String,
  afiliate_wife: String,
  son_1_name: String,
  age_1_son: String,
  afiliate_1_son: String,
  son_2_name: String,
  age_2_son: String,
  afiliate_2_son: String,
  son_3_name: String,
  age_3_son: String,
  afiliate_3_son: String,
  emergency_name: String,
  emergency_phone: String,
  weight: String,
  height: String,
  complexion: String,
  blood_type: String,
  vaccines: String,
  brand_car: String,
  tipe_car: String,
  plates: String,
  decal_folio: String,
  model: String,
  dateCreated: { type: Date, default: Date.now },
});

module.exports = mongoose.model("info", InfoSchema);
